In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# imports

In [5]:
import os
import sys
sys.path.append(f'{os.getcwd()}')
from ult import *
from stable_baselines3 import PPO
from firefly_task import CircularFireflyEnv as Task

SyntaxError: invalid syntax (firefly_task.py, line 193)

# test

In [8]:
import torch



In [10]:
from firefly_task import Model
model=Model(dt=1)
model.reset()
# f,w=model.obs_dynamic()
z, S = model.obs_phase()
print('true w', model.w,'v', model.v)
print(f'belief mu z:{z}, \nbelief cov S:{S}')
print(f'state ft: {model.f_t:.2f}')

# plt.plot(w)
# plt.plot(f+torch.cumsum(w,axis=0)*model.dt)

tensor([-0.2167, -1.0644, -1.9120, -2.7597, -3.6073, -4.4549, -5.3026, -6.1502,
        -6.9979, -7.8455])
('decide selfmotion:tensor([True]), mu_w 0.64 > 0.08',)
(tensor([0.6407]), 'w estimated')
(tensor([-0.2084]), 'v estimated')
('decide object motion:tensor([False]), mu_v -0.21 > 0.22',)
tensor([-0.2167, -1.0644, -1.9120, -2.7597, -3.6073, -4.4549, -5.3026, -6.1502,
        -6.9979, -7.8455])
('decide selfmotion:tensor([True]), mu_w 0.99 > 0.08',)
(tensor([0.9883]), 'w estimated')
(tensor([0.1432]), 'v estimated')
('decide object motion:tensor([False]), mu_v 0.14 > 0.22',)
true w tensor([0.8476]) v tensor([0.])
belief mu z:tensor([-8.2537,  0.1432,  0.0000]), 
belief cov S:tensor([[ 3.5174e-01, -9.9502e-04,  0.0000e+00],
        [-9.9502e-04,  1.5299e-01,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0000e-06]])
state ft: -7.81


In [101]:
model.step(torch.ones(1)*-2)

(tensor([ 5.1008e+00, -2.0842e-01, -6.1153e-01,  5.8833e+02,  1.5299e-01,
          9.4846e+00]),
 tensor([0]),
 True,
 {})

In [41]:
zt, St = model.z
print(([zt.reshape(-1), St[0, 0], St[1, 1], St[0, 1]]))
torch.concat([zt.reshape(-1), St[0, 0].reshape(1), St[1, 1].reshape(1), St[0, 1].reshape(1)])

[tensor([-9.3018, -0.2084,  0.6115]), tensor(0.9597), tensor(0.1530), tensor(0.3050)]


tensor([-9.3018, -0.2084,  0.6115,  0.9597,  0.1530,  0.3050])

In [465]:
from models import Model_NoSM_ControlA as Model

john=Model(t_obs=1, T_control=1)

john.get_threshold_noSM(), john.get_threshold_SM()

john.get_Sigma_move_SM()[[1,3],:][:,[1,3]], john.get_Sigma_stat_SM()[[1,3],:][:,[1,3]],john.get_Sigma_move_noSM()[1:,1:], john.get_Sigma_stat_noSM()

# john.get_Sigma_move_SM(), john.get_Sigma_stat_SM(),john.get_Sigma_move_noSM(), john.get_Sigma_stat_noSM()


(tensor([[ 0.9200, -0.0394],
         [-0.0394,  0.4874]]),
 tensor([[0.9613, 0.1473],
         [0.1473, 0.4874]]),
 tensor([[ 0.8201, -0.0658],
         [-0.0658,  0.5130]], grad_fn=<SliceBackward0>),
 tensor([[0.8585, 0.1551],
         [0.1551, 0.5130]], grad_fn=<MulBackward0>))

In [467]:
True*1

1

In [3]:
# # testing region
# env = Task()
# env.obs_phase()
# # print(env.observations)
# A = [a[0] for a in env.observations]
# B = [a[1] for a in env.observations]
# print('v', B)

# mu, sigma = calculate_mu_sigma(B)
# prob_density_0 = probability_of_zero(mu, sigma)
# print(prob_density_0)


v is 0
v [0.8283250491054964, -1.4036037558408296, 1.903627719591597, 0.9550030944945197, 0.29649228326520405, -0.6575847249233046]
0.3512515264365923
